apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-chatbot
spec:
  replicas: 2

  selector:
    matchLabels:
      app: medical-chatbot

  template:
    metadata:
      labels:
        app: medical-chatbot

    spec:
      containers:
        - name: medical-chatbot
          image: kruthikchethu/medical-chatbot:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: medical-chatbot-service

spec:
  type: LoadBalancer

  selector:
    app: medical-chatbot

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
