apiVersion: v1
kind: Service

metadata:
  name: medical-chatbot-service

spec:
  selector:
    app: medical-chatbot

  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

  type: LoadBalancer
